import 'package:flutter/material.dart';
import 'package:shop_app/screens/splash/splash_screen.dart';

import 'package:provider/provider.dart';
import 'package:shop_app/providers/user_provider.dart';
import 'package:shop_app/services/firestore_service.dart';
import 'package:shop_app/providers/settings_provider.dart';
import 'package:shop_app/providers/product_provider.dart';
import 'package:shop_app/providers/cart_provider.dart';
import 'package:shop_app/providers/notification_provider.dart';

import 'package:firebase_core/firebase_core.dart';
import 'routes.dart';
import 'theme.dart';

// Import is needed but the actual options file will be generated by the user later via flutterfire
import 'firebase_options.dart'; 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize with explicit options to prevent core/no-app error
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Attempt to Seed Database automatically for Demo! (Fails safely if permission denied)
  FirestoreService().seedDatabase();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => SettingsProvider()),
        ChangeNotifierProvider(create: (_) => ProductProvider()),
        ChangeNotifierProvider(create: (_) => CartProvider()),
        ChangeNotifierProvider(create: (_) => NotificationProvider()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<SettingsProvider>(
      builder: (context, settings, child) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'ShopVibe',
          theme: AppTheme.lightTheme(context),
          darkTheme: AppTheme.darkTheme(context),
          themeMode: ThemeMode.dark,
          initialRoute: SplashScreen.routeName,
          routes: routes,
        );
      },
    );
  }
}
